services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sheedbox_db
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "9876:9876"
    depends_on:
      - db
      - redis
    environment:
      - DB_USER=root
      - DB_PASS=secret
      - DB_HOST=db:3306
      - DB_NAME=sheedbox_db
      - REDIS_URL=redis:6379
      - PORT=9876
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      # Mount source code so Air can detect changes
      - .:/app
      # Prevent overwriting the Go module cache inside the container
      - /app/tmp

volumes:
  db_data:
